# Generated by Django 3.2.5 on 2021-08-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem_Categoria', max_length=100)),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem_Titulo', max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=100)),
                ('categoriaId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='aluraflix_api.categorias')),
            ],
        ),
    ]
